from __future__ import annotations

from collections.abc import Callable
from typing import Any


def extend_batch_reliability_schemas(
	schemas: dict[str, dict[str, Any]],
	*,
	schema: Callable[..., dict[str, Any]],
	field: Callable[..., dict[str, Any]],
	select: Callable[..., dict[str, Any]],
	link: Callable[..., dict[str, Any]],
	perm: Callable[..., dict[str, Any]],
) -> None:
	"""Register durable, service-managed batch orchestration audit records."""
	read_permissions = [
		perm("System Manager"),
		perm("IONE QC Administrator"),
		perm("IONE QMS Auditor"),
	]
	schemas.update(
		{
			"IONE Batch Run": schema(
				"IONE Administration",
				[
					field("Run Key", "run_key", reqd=1, unique=1, read_only=1, search_index=1),
					select(
						"Batch Type",
						"batch_type",
						"Indicator\nAnalytics",
						reqd=1,
						read_only=1,
						in_list_view=1,
						in_standard_filter=1,
					),
					field("Subject Key", "subject_key", reqd=1, read_only=1, search_index=1),
					field("Period Start", "period_start", "Date", reqd=1, read_only=1),
					field(
						"Period End",
						"period_end",
						"Date",
						reqd=1,
						read_only=1,
						search_index=1,
					),
					field("Source DocType", "source_doctype", read_only=1),
					field("Source Index", "source_index", "Int", read_only=1),
					select(
						"Status",
						"status",
						"Pending\nRunning\nRetry Waiting\nDead Letter\nCompleted\nSuperseded",
						reqd=1,
						read_only=1,
						in_list_view=1,
						in_standard_filter=1,
					),
					select(
						"Phase",
						"phase",
						"Dispatch\nMaterializing\nVerifying\nReady\nExecuting\nFinal Verifying"
						"\nProjecting\nSnapshot Drift\nComplete",
						reqd=1,
						read_only=1,
					),
					field("Task Path", "task_path", reqd=1, read_only=1),
					field(
						"Task Arguments JSON",
						"task_args_json",
						"Code",
						options="JSON",
						reqd=1,
						read_only=1,
					),
					field("Snapshot Start Cursor", "snapshot_start_cursor", "Long Text", read_only=1),
					field("Cursor JSON", "cursor_json", "Long Text", read_only=1),
					field("High Water JSON", "high_water_json", "Code", options="JSON", read_only=1),
					field(
						"Freshness Watermark JSON",
						"freshness_watermark_json",
						"Code",
						options="JSON",
						read_only=1,
					),
					field("Manifest Hash", "manifest_hash", reqd=1, read_only=1, length=64),
					field("Manifest Record Count", "manifest_record_count", "Int", read_only=1),
					field("Verification Hash", "verification_hash", reqd=1, read_only=1, length=64),
					field(
						"Verification Record Count",
						"verification_record_count",
						"Int",
						read_only=1,
					),
					field("Work Total", "work_total", "Int", read_only=1),
					field("Work Completed", "work_completed", "Int", read_only=1),
					field("Work Receipt Hash", "work_receipt_hash", read_only=1, length=64),
					field("Work Receipt Count", "work_receipt_count", "Int", read_only=1),
					field("Attempt Count", "attempt_count", "Int", read_only=1),
					field("Max Attempts", "max_attempts", "Int", reqd=1, read_only=1),
					field("Next Retry At", "next_retry_at", "Datetime", read_only=1, search_index=1),
					field("Lease Token", "lease_token", read_only=1, hidden=1),
					field(
						"Lease Expires At",
						"lease_expires_at",
						"Datetime",
						read_only=1,
						search_index=1,
					),
					field("Heartbeat At", "heartbeat_at", "Datetime", read_only=1),
					field("Continuation Sequence", "continuation_sequence", "Int", read_only=1),
					field("Last Error Code", "last_error_code", read_only=1),
					link(
						"Failure Work Item",
						"failure_work_item",
						"IONE Batch Work Item",
						read_only=1,
					),
					field("Recovery Generation", "recovery_generation", "Int", reqd=1, read_only=1),
					link("Recovered By", "recovered_by", "User", read_only=1),
					field("Recovered At", "recovered_at", "Datetime", read_only=1),
					field("Recovery Reason", "recovery_reason", "Small Text", read_only=1),
					field("Completed At", "completed_at", "Datetime", read_only=1),
				],
				read_permissions,
				autoname="field:run_key",
				search_fields="run_key,subject_key,status,batch_type",
				allow_import=0,
				track_changes=0,
			),
			"IONE Batch Work Item": schema(
				"IONE Administration",
				[
					field(
						"Item Key",
						"item_key",
						reqd=1,
						unique=1,
						read_only=1,
						search_index=1,
					),
					link(
						"Batch Run",
						"batch_run",
						"IONE Batch Run",
						reqd=1,
						read_only=1,
						search_index=1,
					),
					field("Sequence", "sequence", "Int", reqd=1, read_only=1),
					field(
						"Payload JSON",
						"payload_json",
						"Code",
						options="JSON",
						reqd=1,
						read_only=1,
					),
					field("Payload Hash", "payload_hash", reqd=1, read_only=1, length=64),
					select(
						"Status",
						"status",
						"Pending\nRetry Waiting\nDead Letter\nSucceeded",
						reqd=1,
						read_only=1,
						in_list_view=1,
						in_standard_filter=1,
					),
					field("Attempt Count", "attempt_count", "Int", read_only=1),
					field("Max Attempts", "max_attempts", "Int", reqd=1, read_only=1),
					field("Next Retry At", "next_retry_at", "Datetime", read_only=1, search_index=1),
					field("Last Error Code", "last_error_code", read_only=1),
					field("Result Reference", "result_reference", read_only=1, search_index=1),
					field("Completed At", "completed_at", "Datetime", read_only=1),
				],
				read_permissions,
				autoname="field:item_key",
				search_fields="item_key,batch_run,status,result_reference",
				allow_import=0,
				track_changes=0,
			),
			"IONE Batch Recovery Receipt": schema(
				"IONE Administration",
				[
					field(
						"Receipt Key",
						"receipt_key",
						reqd=1,
						unique=1,
						read_only=1,
						search_index=1,
					),
					link(
						"Batch Run",
						"batch_run",
						"IONE Batch Run",
						reqd=1,
						read_only=1,
						search_index=1,
					),
					field(
						"Recovery Generation",
						"recovery_generation",
						"Int",
						reqd=1,
						read_only=1,
					),
					field("Prior Status", "prior_status", reqd=1, read_only=1),
					field("Reason", "reason", "Small Text", reqd=1, read_only=1),
					field("Reason Hash", "reason_hash", reqd=1, read_only=1, length=64),
					link(
						"Requested By",
						"requested_by",
						"User",
						reqd=1,
						read_only=1,
					),
					field(
						"Requested At",
						"requested_at",
						"Datetime",
						reqd=1,
						read_only=1,
					),
				],
				read_permissions,
				autoname="field:receipt_key",
				search_fields="receipt_key,batch_run,requested_by",
				allow_import=0,
				track_changes=0,
			),
		}
	)
